# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('begin_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, default='', max_length=64)),
                ('activity_group_name', models.CharField(blank=True, default='', max_length=100)),
                ('admin_user', models.ManyToManyField(related_name='admin_activity_group', to='account.Profile')),
                ('normal_user', models.ManyToManyField(related_name='normal_activity_group', to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_log', to='information.Activity')),
                ('register_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_log', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='information.ActivityGroup'),
        ),
    ]
