# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerlog',
            name='register_time',
            field=models.DateTimeField(auto_created=True, blank=True, default='2016-10-12T00:00:00Z'),
        ),
    ]
