# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
