# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(blank=True, upload_to='face_image/%Y/%m/%d')),
                ('face_id', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genders', models.IntegerField(default=0)),
                ('school', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=60)),
                ('real_name', models.CharField(blank=True, default='', max_length=50)),
                ('tel', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(default='', max_length=30)),
                ('icon_image', models.ImageField(blank=True, upload_to='icon_image/%Y/%m/%d')),
                ('person_id', models.CharField(blank=True, default='', max_length=50)),
                ('email_auth', models.BooleanField(default=False)),
                ('email_hash', models.CharField(blank=True, max_length=30)),
                ('is_term_camera', models.BooleanField(default=False)),
                ('term_position', models.CharField(blank=True, default='', max_length=50)),
                ('password_hash', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('account.look', '查看全部User'),),
            },
        ),
        migrations.AddField(
            model_name='face',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face', to='account.Profile'),
        ),
    ]
