# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_hash',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
