# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161014_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_term_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='term_position',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
