# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161016_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_hash',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
